name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
	required: true
	default: "World"
  YOUR_NAME:
	description: "Who to greet"
	required: true
	defaul: "Raymond"
runs:
	using: "docker"
	image: "Dockerfile"
branding:
	icon: "mic"
	color: "purple"
